/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 13 03:32:39 GMT 2019
 */

package com.saud_dev.technology_assessment.model.receipt;

import org.junit.Test;
import static org.junit.Assert.*;
import com.saud_dev.technology_assessment.model.item.Item;
import com.saud_dev.technology_assessment.model.receipt.Receipt;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Receipt_ESTest extends Receipt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Receipt receipt0 = new Receipt();
      receipt0.setTimeAsCustomer("1slgvC_X");
      String string0 = receipt0.getTimeAsCustomer();
      assertEquals("1slgvC_X", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Receipt receipt0 = new Receipt();
      receipt0.setTimeAsCustomer("");
      String string0 = receipt0.getTimeAsCustomer();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Receipt receipt0 = new Receipt();
      LinkedList<Item> linkedList0 = new LinkedList<Item>();
      Item item0 = new Item();
      linkedList0.add(item0);
      receipt0.setItems(linkedList0);
      List<Item> list0 = receipt0.getItems();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Receipt receipt0 = new Receipt();
      receipt0.setCustomer("");
      String string0 = receipt0.getCustomer();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Receipt receipt0 = new Receipt();
      String string0 = receipt0.getTimeAsCustomer();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Receipt receipt0 = new Receipt();
      List<Item> list0 = receipt0.getItems();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Receipt receipt0 = new Receipt();
      receipt0.setCustomer("*m)V");
      String string0 = receipt0.getCustomer();
      assertEquals("*m)V", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Receipt receipt0 = new Receipt();
      String string0 = receipt0.getCustomer();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Receipt receipt0 = new Receipt();
      LinkedList<Item> linkedList0 = new LinkedList<Item>();
      receipt0.setItems(linkedList0);
      List<Item> list0 = receipt0.getItems();
      assertEquals(0, list0.size());
  }
}
