/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 13 01:32:45 GMT 2019
 */

package com.saud_dev.technology_assessment.constants;

import org.junit.Test;
import static org.junit.Assert.*;
import com.saud_dev.technology_assessment.constants.Constants;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Constants_ESTest extends Constants_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Constants constants0 = new Constants();
  }
}
