/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 13 03:32:04 GMT 2019
 */

package com.saud_dev.technology_assessment.model.customer;

import org.junit.Test;
import static org.junit.Assert.*;
import com.saud_dev.technology_assessment.model.customer.Customer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Customer_ESTest extends Customer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Customer customer0 = new Customer();
      Double double0 = new Double(2.0);
      customer0.setTimeAsCustomer(double0);
      double double1 = customer0.getDiscount();
      assertEquals(2.0, customer0.getTimeAsCustomer(), 0.01);
      assertEquals(0.05, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Customer customer0 = new Customer();
      Double double0 = customer0.getTimeAsCustomer();
      assertEquals(0.0, (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Customer customer0 = new Customer();
      assertEquals(0.0, customer0.getTimeAsCustomer(), 0.01);
      
      Double double0 = new Double((-1.0));
      customer0.setTimeAsCustomer(double0);
      customer0.getTimeAsCustomer();
      assertEquals((-1.0), customer0.getTimeAsCustomer(), 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Customer customer0 = new Customer(1.0);
      Double double0 = new Double(1.0);
      customer0.setTimeAsCustomer(double0);
      assertEquals(1.0, customer0.getTimeAsCustomer(), 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Customer customer0 = new Customer(1.0);
      Double double0 = customer0.getTimeAsCustomer();
      assertEquals(1.0, (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Customer customer0 = new Customer();
      customer0.setTimeAsCustomer((Double) null);
      assertEquals(0.0, customer0.getTimeAsCustomer(), 0.01);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      long long0 = Customer.getSerialversionuid();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Customer customer0 = new Customer(2367.590047486442);
      double double0 = customer0.getDiscount();
      assertEquals(0.05, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Customer customer0 = new Customer();
      double double0 = customer0.getDiscount();
      assertEquals(0.0, double0, 0.01);
      assertEquals(0.0, customer0.getTimeAsCustomer(), 0.01);
  }
}
