/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 14 17:40:49 GMT 2019
 */

package com.saud_dev.technology_assessment;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.saud_dev.technology_assessment.TechnologyAssessmentApplication;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TechnologyAssessmentApplication_ESTest extends TechnologyAssessmentApplication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TechnologyAssessmentApplication technologyAssessmentApplication0 = new TechnologyAssessmentApplication();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "";
      // Undeclared exception!
      try { 
        TechnologyAssessmentApplication.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.springframework.boot.autoconfigure.condition.OnClassCondition", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TechnologyAssessmentApplication technologyAssessmentApplication0 = new TechnologyAssessmentApplication();
      String[] stringArray0 = new String[6];
      stringArray0[0] = "spring.boot.enableautoconfiguration";
      stringArray0[1] = "";
      stringArray0[2] = "&74up";
      stringArray0[3] = "";
      stringArray0[4] = "Z>e:IT ,Rh#u=";
      stringArray0[5] = "";
      // Undeclared exception!
      try { 
        TechnologyAssessmentApplication.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.springframework.boot.autoconfigure.condition.OnClassCondition", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "W}/7QKH8";
      stringArray0[1] = "[C9O0/q~@Oq&";
      stringArray0[2] = "spring.boot.enableautoconfiguration";
      stringArray0[3] = "k0%i0+Yw\"-|Hk}";
      stringArray0[4] = "L0.AFsg";
      stringArray0[5] = "spring.boot.enableautoconfiguration";
      stringArray0[6] = "";
      stringArray0[7] = "";
      stringArray0[8] = "H$iS";
      // Undeclared exception!
      try { 
        TechnologyAssessmentApplication.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.springframework.boot.autoconfigure.condition.OnClassCondition", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TechnologyAssessmentApplication technologyAssessmentApplication0 = new TechnologyAssessmentApplication();
      String[] stringArray0 = new String[5];
      stringArray0[0] = "";
      stringArray0[1] = "Hl#_";
      stringArray0[2] = "";
      stringArray0[3] = ";*+)4n";
      stringArray0[4] = "";
      // Undeclared exception!
      try { 
        TechnologyAssessmentApplication.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.springframework.boot.autoconfigure.condition.OnClassCondition", e);
      }
  }
}
