/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 14 17:39:39 GMT 2019
 */

package com.saud_dev.technology_assessment.model.customer;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.junit.Test;

public class CustomerFactory_Test {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        CustomerFactory.createCustomer("s&zzOyCU4] Ac?`r", "");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        CustomerFactory.createCustomer((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Customer customer0 = CustomerFactory.createCustomer("employee", "employee");
      assertEquals(0.0, customer0.getTimeAsCustomer(), 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Customer customer0 = CustomerFactory.createCustomer("affiliate", "affiliate");
      assertEquals(1L, customer0.getSerialversionuid());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Customer customer0 = CustomerFactory.createCustomer("bffiliate", (String) null);
      assertEquals(0.0, customer0.getTimeAsCustomer(), 0.01);
  }
}
