/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 14 17:41:16 GMT 2019
 */

package com.saud_dev.technology_assessment.model.customer;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class Customer_ESTest extends Customer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Customer customer0 = new Customer();
      Double double0 = new Double(2.0);
      customer0.setTimeAsCustomer(double0);
      double double1 = customer0.getDiscount();
      assertEquals(2.0, customer0.getTimeAsCustomer(), 0.01);
      assertEquals(0.05, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Customer customer0 = new Customer();
      Double double0 = customer0.getTimeAsCustomer();
      assertEquals(0.0, (double)double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Customer customer0 = new Customer();
      Double double0 = new Double(2.0);
      customer0.setTimeAsCustomer(double0);
      customer0.getTimeAsCustomer();
      assertEquals(0.05, customer0.getDiscount(), 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Customer customer0 = new Customer(0.05);
      Double double0 = new Double((-1.0));
      customer0.setTimeAsCustomer(double0);
      customer0.getTimeAsCustomer();
      assertEquals((-1.0), customer0.getTimeAsCustomer(), 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Customer customer0 = new Customer(1L);
      double double0 = customer0.getDiscount();
      assertEquals(1.0, customer0.getTimeAsCustomer(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      long long0 = Customer.getSerialversionuid();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Customer customer0 = new Customer();
      customer0.setTimeAsCustomer((Double) null);
      assertEquals(0.0, customer0.getTimeAsCustomer(), 0.01);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Customer customer0 = new Customer(1548.7178317655926);
      double double0 = customer0.getDiscount();
      assertEquals(0.05, double0, 0.01);
  }
}
