/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 14 17:29:34 GMT 2019
 */

package com.saud_dev.technology_assessment.model.customer;

import org.junit.Test;
import static org.junit.Assert.*;
import com.saud_dev.technology_assessment.model.customer.Employee;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Employee_ESTest extends Employee_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Employee employee0 = new Employee();
      double double0 = employee0.getDiscount();
      assertEquals(0.3, double0, 0.01);
  }
}
