/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 14 17:29:34 GMT 2019
 */

package com.saud_dev.technology_assessment.model.customer;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class Employee_Test {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Employee employee0 = new Employee();
      double double0 = employee0.getDiscount();
      assertEquals(0.3, double0, 0.01);
  }
}
