/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 13 01:38:26 GMT 2019
 */

package com.saud_dev.technology_assessment.model.item;

import org.junit.Test;
import static org.junit.Assert.*;
import com.saud_dev.technology_assessment.model.item.Item;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Item_ESTest extends Item_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Item item0 = new Item();
      item0.setValue("com.saud_dev.technology_assessment.model.item.Item");
      String string0 = item0.getValue();
      assertEquals("com.saud_dev.technology_assessment.model.item.Item", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Item item0 = new Item();
      item0.setValue("");
      String string0 = item0.getValue();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Item item0 = new Item();
      item0.setType("");
      String string0 = item0.getType();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getValue();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Item item0 = new Item();
      item0.setType("udl\"S)WkGaO\"c,Er");
      String string0 = item0.getType();
      assertEquals("udl\"S)WkGaO\"c,Er", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Item item0 = new Item();
      String string0 = item0.getType();
      assertNull(string0);
  }
}
