/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 14 17:42:45 GMT 2019
 */

package com.saud_dev.technology_assessment.rest;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.saud_dev.technology_assessment.model.item.Item;
import com.saud_dev.technology_assessment.model.receipt.Receipt;
import com.saud_dev.technology_assessment.rest.TechnologyAssessmentRestController;
import com.saud_dev.technology_assessment.service.TechnologyAssessmentService;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TechnologyAssessmentRestController_ESTest extends TechnologyAssessmentRestController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TechnologyAssessmentRestController technologyAssessmentRestController0 = new TechnologyAssessmentRestController();
      TechnologyAssessmentService technologyAssessmentService0 = new TechnologyAssessmentService();
      Receipt receipt0 = new Receipt();
      LinkedList<Item> linkedList0 = new LinkedList<Item>();
      Item item0 = mock(Item.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(item0).getValue();
      linkedList0.add(item0);
      receipt0.setCustomer("Oi");
      receipt0.setItems(linkedList0);
      // Undeclared exception!
      try { 
        technologyAssessmentRestController0.getCustomerDiscountedReceipt(receipt0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Receipt receipt0 = new Receipt();
      TechnologyAssessmentRestController technologyAssessmentRestController0 = new TechnologyAssessmentRestController();
      TechnologyAssessmentService technologyAssessmentService0 = new TechnologyAssessmentService();
      Injector.inject(technologyAssessmentRestController0, (Class<?>) TechnologyAssessmentRestController.class, "service", (Object) technologyAssessmentService0);
      Injector.validateBean(technologyAssessmentRestController0, (Class<?>) TechnologyAssessmentRestController.class);
      // Undeclared exception!
      try { 
        technologyAssessmentRestController0.getCustomerDiscountedReceipt(receipt0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // 400 BAD_REQUEST \"Invalid parameter, customer cannot be empty\"
         //
         verifyException("com.saud_dev.technology_assessment.validators.ReceiptValidator", e);
      }
  }
}
